### ISSUE TITLE
Not working with new Slack API

### ISSUE THREAD

**Issue by jramboz** [meltaxa/slackview#1]
Installed per instructions, but I get the following error:

>Array ( [ok] => [error] => method_deprecated [response_metadata] => Array ( [messages] => Array ( [0] => [ERROR] This method is retired and can no longer be used. Please use conversations.list or users.conversations instead. Learn more: https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api. ) ) ) Could not execute request channels.list

It seems the offender is the channel.* API calls. These have been replaced by conversations.*; however, the return data seems to be in a different format than the deprecated methods.

Please consider updating to the new API methods.

**Comment by meltaxa** [comment]
Hi @jramboz, thanks for letting me know about the new API methods. Seems all new apps have to use it, while existing apps have a grace period. I've made changes on the #1-slack-api-updates branch. My own tests were successful but let me know if that resolves the issue at your end.

**Comment by jramboz** [comment]
@meltaxa Confirmed working from the new branch. Thanks so much for the quick update!

**Comment by meltaxa** [comment]
Awesome. Branch merged to master.
