### ISSUE TITLE
Fixing Error: Could not execute request conversations.history

### ISSUE THREAD

**Issue by mcknightd** [meltaxa/slackview#2]
Hello, 

On following the instructions, I received this error.
Array ( [ok] => [error] => not_in_channel ) Could not execute request conversations.history

After looking into it, I found that after creating the app, you need to join your slack channel and use `\invite @SlackView` to invite the "bot" it to join. This would be a good addition to the instructions.

**Comment by meltaxa** [comment]
Hi @mcknightd, thanks for the feedback. The README has been updated accordingly. Cheers.
